import React, { useState } from "react";
import "../css/tip-page.css";
import { ArrowRight, Check, Heart, Mic2, Play, Sparkles, Users, Volume2, Zap } from "lucide-react";
import Logo from "./Logo";

export default function TipPage() {
  const [amount,setAmount]=useState(250);
  const [voice,setVoice]=useState("Natural");
  return <div className="tip-page"><div className="tip-top"><Logo/><span><span className="live-dot"/> alexplays is live</span></div><div className="tip-layout"><div className="tip-intro"><div className="creator-big">A</div><div className="eyebrow">SUPPORT ALEX</div><h1>Make their<br/><em>day.</em></h1><p>Your support keeps the stream going. Add a message, choose a voice and make some noise.</p><div className="tip-social"><span><Users size={15}/> 1.8K watching</span><span><Heart size={15}/> 24K followers</span></div></div><div className="tip-card"><div className="tip-card-head"><div><h2>Send a tip</h2><p>It'll pop up live on stream.</p></div><Sparkles size={19}/></div><label>Amount</label><div className="amounts">{[50,100,250,500,1000].map(x=><button className={amount===x?"selected":""} onClick={()=>setAmount(x)} key={x}>₹{x.toLocaleString()}</button>)}</div><div className="custom-amount"><span>₹</span><input value={amount} onChange={e=>setAmount(Number(e.target.value)||0)}/></div><label>Your name</label><input className="tip-input" placeholder="How should we call you?"/><label>Message <span>optional</span></label><textarea className="tip-input" rows="3" placeholder="Say something nice..."/><label>Voice narration</label><div className="voice-grid">{["Natural","Deep","Funny","Robot"].map(v=><button className={voice===v?"selected":""} onClick={()=>setVoice(v)} key={v}><Volume2 size={15}/>{v}<Play size={11}/></button>)}</div><label>Sound effect <span>optional</span></label><div className="sound-row"><button><Zap size={15}/> Airhorn</button><button><Mic2 size={15}/> Applause</button><button><Play size={14}/> Drumroll</button></div><button className="btn btn-primary tip-submit">Send ₹{amount.toLocaleString()} tip <ArrowRight size={17}/></button><small className="secure-note"><Check size={13}/> Secure checkout · Powered by StreamTips</small></div></div></div>;
}
